COA:
  dataset_params:
    train:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_trainA.txt'
      cache_folder: './cache/COA/'
    val:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_valA.txt'
      cache_folder: './cache/COA/'
    test:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_testA.txt'
      cache_folder: './cache/COA/'
COB:
  dataset_params:
    train:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_trainB.txt'
      cache_folder: './cache/COB/''
    val:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_valB.txt'
      cache_folder: './cache/COB/'
    test:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_testB.txt'
      cache_folder: './cache/COB/'
COC:
  dataset_params:
    train:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_trainC.txt'
      cache_folder: './cache/COC/'
    val:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_valC.txt'
      cache_folder: './cache/COC/'
    test:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_testC.txt'
      cache_folder: './cache/COC/'