COA:
  dataset_params:
    train:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_trainA.txt'
    val:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_valA.txt'
    test:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_testA.txt'

COB:
  dataset_params:
    train:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_trainB.txt'
    val:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_valB.txt'
    test:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_testB.txt'

COC:
  dataset_params:
    train:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_trainC.txt'
    val:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_valC.txt'
    test:
      series_list_path: '/hdd/openfl_system_inference_test/fl_cmp_testC.txt'