root: './data/lung_nodule'
database:
  dicom: 'dicom.db'
  fl: 'fl.db'
  process: 'process.db'
ftp: 'FTP'
dicom: 'dicom'
record: 'record'

working_dir: 'working_dir'
data:
  train_set: 'train.txt'
  val_set: 'val.txt'