common:
  seed: 1029
  enable_progress_bar: True
  save_dir: './save'
  save_local_state: False

server:
  total_rounds: 60
  best_model_metric_name: f1_score

  model: 
    template: fl_modules.model.stage2.stage2_model.Stage2Model
    params:
      base_planes: 16
  
  ema:
    apply: False
    params:
      decay: 0.99

  optimizer: 
    template: torch.optim.Adam
    params:
      lr: 0.0005

  actions:
    train:
      template: fl_modules.client.stage2_logic.train
      params:
        num_epoch: 1
        batch_size: 64
    val:
      template: fl_modules.client.stage2_logic.validation
      params:
        batch_size: 64
    test:
      template: fl_modules.client.stage2_logic.test
      params:
        batch_size: 64

  aggregation:
    optimizer_aggregate_strategy: continue_global # continue_global, continue_local, reset
    template:
      fl_modules.server.aggregation.fedavg.FedAvg
    params:
      model:
        keep_local_state: []
      optimizer:
        keep_local_state: [] # If strategy is not continue_global, this field is ignored.

client:
  nodule_size_ranges: # pixel size
    benign: [0, 52] 
    probably_benign: [52, 176] 
    probably_suspicious: [176, 418]
    suspicious: [418, -1]
    
  dataset:
    template: fl_modules.dataset.stage2_dataset.Stage2Dataset
    params:
      crop_settings: # (y, x, z)
        large_shape:  [80, 80, 30]
        medium_shape: [60, 60, 20]
        small_shape:  [40, 40, 10]
        final_shape:  [80, 80, 30, 1]