COA:
  dataset_params:
    train:
      series_list_path: './data/new_unlabeled/client0_r02_labeled_train.txt'
    unlabeled_train:
      series_list_path: './data/new_unlabeled/client0_r02_unlabeled_train.txt'
    unlabeled_det:
      series_list_path: './data/new_unlabeled/client0_r02_unlabeled_train.txt'
    val:
      series_list_path: './data/client0_val.txt'
    test:
      series_list_path: './data/client0_test.txt'

COB:
  dataset_params:
    train:
      series_list_path: './data/new_unlabeled/client1_r02_labeled_train.txt'
    unlabeled_train:
      series_list_path: './data/new_unlabeled/client1_r02_unlabeled_train.txt'
    unlabeled_det:
      series_list_path: './data/new_unlabeled/client1_r02_unlabeled_train.txt'
    val:
      series_list_path: './data/client1_val.txt'
    test:
      series_list_path: './data/client1_test.txt'

COC:
  dataset_params:
    train:
      series_list_path: './data/new_unlabeled/client2_r02_labeled_train.txt'
    unlabeled_train:
      series_list_path: './data/new_unlabeled/client2_r02_unlabeled_train.txt'
    unlabeled_det:
      series_list_path: './data/new_unlabeled/client2_r02_unlabeled_train.txt'
    val:
      series_list_path: './data/client2_val.txt'
    test:
      series_list_path: './data/client2_test.txt'