COA:
  dataset_params:
    train:
      series_list_path: './data/lung_nodule/small_train.txt'
    val:
      series_list_path: './data/lung_nodule/small_train.txt'
    test:
      series_list_path: './data/lung_nodule/small_train.txt'

COB:
  dataset_params:
    train:
      series_list_path: './data/lung_nodule/small_train.txt'
    val:
      series_list_path: './data/lung_nodule/small_train.txt'
    test:
      series_list_path: './data/lung_nodule/small_train.txt'

COC:
  dataset_params:
    train:
      series_list_path: './data/lung_nodule/small_train.txt'
    val:
      series_list_path: './data/lung_nodule/small_train.txt'
    test:
      series_list_path: './data/lung_nodule/small_train.txt'