COA:
  dataset_params:
    train:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'
    val:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'
    test:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'

COB:
  dataset_params:
    train:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'
    val:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'
    test:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'

COC:
  dataset_params:
    train:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'
    val:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'
    test:
      series_list_path: '/disk/HDD1/FL/openfl_system_inference_test/small_train.txt'